version: '3.1'

services:

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres-d3v-pass
    volumes:
      - drop-cases:/var/lib/postgresql/data
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  drop-cases:
